### ISSUE TITLE
Common Abbreviations

### ISSUE THREAD

**Issue by indolering** [emgee3/namecase#1]
I'm planning on using your parser to clean company names, which are littered with LLC, Inc, CO, etc.

Would a PR adding support for these acronyms be welcome?  Perhaps it would be included in a different mode?

**Comment by mikkelking** [comment]
I'm not the author, but I would have thought that if you add another option to process LLC etc and 

  * it doesn't impact the existing processing
  * You add in tests to exercise your code
  * You update the documentation

Then it wouldn't be a problem, accepting the PR becomes as simple as clicking a button. You can always fork the package and expllicitly reference your fork of it when you do `npm install`

**Comment by indolering** [comment]
I'm no longer working on this.
